-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 10:50:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenciaDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agenciaDB` ;

-- -----------------------------------------------------
-- Schema agenciaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenciaDB` DEFAULT CHARACTER SET utf8 ;
USE `agenciaDB` ;

-- -----------------------------------------------------
-- Table `agenciaDB`.`Agencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenciaDB`.`Agencia` ;

CREATE TABLE IF NOT EXISTS `agenciaDB`.`Agencia` (
  `RFC` VARCHAR(13) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`RFC`),
  UNIQUE INDEX `RFC_UNIQUE` (`RFC` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenciaDB`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenciaDB`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `agenciaDB`.`Cliente` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Agencia_RFC` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  INDEX `fk_Cliente_Agencia1_idx` (`Agencia_RFC` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Agencia1`
    FOREIGN KEY (`Agencia_RFC`)
    REFERENCES `agenciaDB`.`Agencia` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenciaDB`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenciaDB`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `agenciaDB`.`Proveedor` (
  `Codigo` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenciaDB`.`Automovil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenciaDB`.`Automovil` ;

CREATE TABLE IF NOT EXISTS `agenciaDB`.`Automovil` (
  `Codigo` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Año` DATE NOT NULL,
  `Costo` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Motor` VARCHAR(45) NOT NULL,
  `Agencia_RFC` VARCHAR(13) NOT NULL,
  `Proveedor_Codigo` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Automovil_Agencia1_idx` (`Agencia_RFC` ASC) VISIBLE,
  INDEX `fk_Automovil_Proveedor1_idx` (`Proveedor_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Automovil_Agencia1`
    FOREIGN KEY (`Agencia_RFC`)
    REFERENCES `agenciaDB`.`Agencia` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Automovil_Proveedor1`
    FOREIGN KEY (`Proveedor_Codigo`)
    REFERENCES `agenciaDB`.`Proveedor` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenciaDB`.`Cliente_has_Automovil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenciaDB`.`Cliente_has_Automovil` ;

CREATE TABLE IF NOT EXISTS `agenciaDB`.`Cliente_has_Automovil` (
  `Cliente_Codigo` INT NOT NULL,
  `Automovil_Codigo` INT NOT NULL,
  PRIMARY KEY (`Cliente_Codigo`, `Automovil_Codigo`),
  INDEX `fk_Cliente_has_Automovil_Automovil1_idx` (`Automovil_Codigo` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Automovil_Cliente_idx` (`Cliente_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Automovil_Cliente`
    FOREIGN KEY (`Cliente_Codigo`)
    REFERENCES `agenciaDB`.`Cliente` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Automovil_Automovil1`
    FOREIGN KEY (`Automovil_Codigo`)
    REFERENCES `agenciaDB`.`Automovil` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenciaDB`.`Agencia_has_Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenciaDB`.`Agencia_has_Proveedor` ;

CREATE TABLE IF NOT EXISTS `agenciaDB`.`Agencia_has_Proveedor` (
  `Agencia_RFC` VARCHAR(13) NOT NULL,
  `Proveedor_Codigo` INT NOT NULL,
  PRIMARY KEY (`Agencia_RFC`, `Proveedor_Codigo`),
  INDEX `fk_Agencia_has_Proveedor_Proveedor1_idx` (`Proveedor_Codigo` ASC) VISIBLE,
  INDEX `fk_Agencia_has_Proveedor_Agencia1_idx` (`Agencia_RFC` ASC) VISIBLE,
  CONSTRAINT `fk_Agencia_has_Proveedor_Agencia1`
    FOREIGN KEY (`Agencia_RFC`)
    REFERENCES `agenciaDB`.`Agencia` (`RFC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agencia_has_Proveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_Codigo`)
    REFERENCES `agenciaDB`.`Proveedor` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
